# Generated by Django 5.1.7 on 2025-03-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksblog', '0002_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='books', to='booksblog.author', verbose_name='Авторы'),
        ),
    ]
