# Generated by Django 5.1.7 on 2025-03-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksblog', '0004_remove_book_author_delete_author_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Средний рейтинг'),
        ),
    ]
