# Generated by Django 5.1.7 on 2025-03-28 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksblog', '0005_book_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book', to='booksblog.genres', verbose_name='Жанры'),
        ),
    ]
